# Generated by Django 4.2.5 on 2023-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pergunta_delete_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='respostacerta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='pergunta_texto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='resposta1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='resposta2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='resposta3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='resposta4',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
