# Generated by Django 4.2.5 on 2023-12-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_pergunta_respostacerta_alter_pergunta_pergunta_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='solucao',
            field=models.ImageField(blank=True, null=True, upload_to='assets/'),
        ),
    ]
