# Generated by Django 4.2.5 on 2023-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_pergunta_solucao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='categoria',
            field=models.CharField(blank=True, choices=[('geometria_plana', 'Geometria Plana'), ('operacoes_basicas', 'Operações Básicas'), ('fracoes', 'Frações'), ('porcentagens', 'Porcentagens')], max_length=20),
        ),
    ]
