# Generated by Django 4.2.5 on 2023-12-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
    ]
